version: '3'

tasks:
  default:
    desc: default (print all ifs)
    cmds:
      - go run main.go
  openlive:
    desc: Run pcap.OpenLive() example
    dir: cmd/openlive
    cmds:
      - go build
      - sudo ./openlive
  fmtvet:
    desc: go fmt and go vet
    cmds:
      - go fmt ./...
      - go vet ./...
      - staticcheck ./...
      - revive ./...
