version: '3'

tasks:
  default:
    desc: default (print all ifs)
    cmds:
      - go run main.go
  fmtvet:
    desc: go fmt and go vet
    cmds:
      - go fmt ./...
      - go vet ./...
      - staticcheck ./...
      - revive ./...
  packet:
    desc: See *pcap.Packet structure info
    dir: cmd/packet
    cmds:
      - go build
      - cmd: sudo bash ./app.sh
        ignore_error: true
      - sleep 1
      - cmd: sudo bash ./server.sh
        ignore_error: true
      - cmd: sudo bash ./client.sh
        ignore_error: true
      - sleep 3
      - cmd: sudo bash ./kill.sh
        ignore_error: true
  bpffilter:
    desc: Run pcap.OpenOffline() with BPF Filter
    dir: cmd/bpffilter
    cmds:
      - rm -rf *.pid *.pcap
      - go build
      - cmd: sudo bash ./tcpdump.sh
        ignore_error: true
      - cmd: bash ./ping.sh
        ignore_error: true
      - cmd: sudo bash ./kill.sh
        ignore_error: true
      # tcpdumpがpcapファイルを出力する猶予を与える
      - sleep 1
      - sudo ./bpffilter
  openlive:
    desc: Run pcap.OpenLive() example
    dir: cmd/openlive
    cmds:
      - go build
      - sudo ./openlive
  openoffline:
    desc: Run pcap.OpenOffline() example
    dir: cmd/openoffline
    cmds:
      - go build
      - cmd: sudo timeout 3s tcpdump -i eth0 -w example.pcap 'tcp'
        ignore_error: true
      - sudo ./openoffline
  layertype-app:
    desc: See gopacket.Packet.ApplicationLayer() info
    dir: cmd/layertype/app
    cmds:
      - go build
      - sudo bash ./tcpdump.sh
      - sudo bash ./server.sh
      - sleep 1
      - sudo bash ./client.sh
      - sleep 3
      - sudo bash ./kill.sh
      - sleep 1
      - sudo ./app
  layertype-ethernet:
    desc: See *layers.Ethernet info
    dir: cmd/layertype/ethernet
    cmds:
      - go build
      - sudo ./ethernet
  layertype-arp:
    desc: See *layers.ARP info
    dir: cmd/layertype/arp
    cmds:
      - go build
      - sudo bash ./arp-scan.sh &
      - sudo ./arp
  layertype-ipv4:
    desc: See *layers.IPv4 info
    dir: cmd/layertype/ipv4
    cmds:
      - go build
      - sudo ./ipv4
  layertype-tcp:
    desc: See *layers.TCP info
    dir: cmd/layertype/tcp
    cmds:
      - go build
      - sudo ./tcp
  layertype-udp:
    desc: See *layers.UDP info
    dir: cmd/layertype/udp
    cmds:
      - go build
      - cmd: sudo bash ./app.sh
        ignore_error: true
      - sleep 1
      - cmd: sudo bash ./server.sh
        ignore_error: true
      - cmd: sudo bash ./client.sh
        ignore_error: true
      - sleep 3
      - cmd: sudo bash ./kill.sh
        ignore_error: true
  layertype-icmpv4:
    desc: See *layers.ICMPv4 info
    dir: cmd/layertype/icmpv4
    cmds:
      - go build
      - sudo bash ./ping.sh &
      - sudo ./icmpv4
  applayer-http:
    desc: See HTTP info
    dir: cmd/applayer/http
    cmds:
      - go build -o webserver server/main.go
      - go build -o http main.go
      - ./webserver &
      - sudo ./http &
      - sleep 1
      - curl --silent http://localhost:12345/ > /dev/null
      - sleep 3
      - pkill webserver
      - sudo pkill http
  applayer-dns:
    desc: See DNS info
    dir: cmd/applayer/dns
    cmds:
      - go build -o dns main.go
      - sudo ./dns &
      - cmd: sleep 1
        silent: true    
      - dig +noall google.com
      - cmd: sleep 3
        silent: true
      - sudo pkill dns
  applayer-dnssec:
    desc: See DNSSEC info
    dir: cmd/applayer/dnssec
    cmds:
      - go build -o dnssec main.go
      - sudo ./dnssec &
      - cmd: sleep 1
        silent: true
        # https://access.redhat.com/documentation/ja-jp/red_hat_enterprise_linux/7/html/security_guide/sec-security_guide-using-dig-with-dnssec
      - dig +noall +dnssec iij.ad.jp
      - cmd: sleep 3
        silent: true
        # https://eng-blog.iij.ad.jp/archives/7689
      - dig +noall iij.ad.jp dnskey
      - cmd: sleep 3
        silent: true
      - sudo pkill dnssec
  applayer-dhcp:
    desc: See DHCP info
    dir: cmd/applayer/dhcp
    cmds:
      - go build -o dhcp main.go
      - sudo ./dhcp &
      - cmd: sleep 1
        silent: true
      - cmd: sleep 3
        silent: true
      - sudo pkill dhcp
  applayer-ftp:
    desc: See FTP info
    dir: cmd/applayer/ftp
    cmds:
      - cmd: echo Please start the FTP server in advance.
        silent: true
      - go build -o gopacket-ftp main.go
      - sudo ./gopacket-ftp &
      - cmd: read
        silent: true
      - sudo pkill gopacket-ftp
