version: '3'

tasks:
  default:
    desc: default (print all ifs)
    cmds:
      - go run main.go
  openlive:
    desc: Run pcap.OpenLive() example
    dir: cmd/openlive
    cmds:
      - go build
      - sudo ./openlive
  openoffline:
    desc: Run pcap.OpenOffline() example
    dir: cmd/openoffline
    cmds:
      - go build
      - cmd: sudo timeout 3s tcpdump -i eth0 -w example.pcap 'tcp'
        ignore_error: true
      - sudo ./openoffline
  layertype-ethernet:
    desc: See *layers.Ethernet info
    dir: cmd/layertype/ethernet
    cmds:
      - go build
      - sudo ./ethernet
  layertype-arp:
    desc: See *layers.ARP info
    dir: cmd/layertype/arp
    cmds:
      - go build
      - sudo bash ./arp-scan.sh &
      - sudo ./arp
  layertype-ipv4:
    desc: See *layers.IPv4 info
    dir: cmd/layertype/ipv4
    cmds:
      - go build
      - sudo ./ipv4
  layertype-tcp:
    desc: See *layers.TCP info
    dir: cmd/layertype/tcp
    cmds:
      - go build
      - sudo ./tcp
  layertype-udp:
    desc: See *layers.UDP info
    dir: cmd/layertype/udp
    cmds:
      - go build
      - cmd: sudo bash ./app.sh
        ignore_error: true
      - sleep 1
      - cmd: sudo bash ./server.sh
        ignore_error: true
      - cmd: sudo bash ./client.sh
        ignore_error: true
      - sleep 3
      - cmd: sudo bash ./kill.sh
        ignore_error: true
  layertype-icmpv4:
    desc: See *layers.ICMPv4 info
    dir: cmd/layertype/icmpv4
    cmds:
      - go build
      - sudo bash ./ping.sh &
      - sudo ./icmpv4
  packet:
    desc: See *pcap.Packet structure info
    dir: cmd/packet
    cmds:
      - go build
      - cmd: sudo bash ./app.sh
        ignore_error: true
      - sleep 1
      - cmd: sudo bash ./server.sh
        ignore_error: true
      - cmd: sudo bash ./client.sh
        ignore_error: true
      - sleep 3
      - cmd: sudo bash ./kill.sh
        ignore_error: true
  bpffilter:
    desc: Run pcap.OpenOffline() with BPF Filter
    dir: cmd/bpffilter
    cmds:
      - rm -rf *.pid *.pcap
      - go build
      - cmd: sudo bash ./tcpdump.sh
        ignore_error: true
      - cmd: bash ./ping.sh
        ignore_error: true
      - cmd: sudo bash ./kill.sh
        ignore_error: true
      # tcpdumpがpcapファイルを出力する猶予を与える
      - sleep 1
      - sudo ./bpffilter
  fmtvet:
    desc: go fmt and go vet
    cmds:
      - go fmt ./...
      - go vet ./...
      - staticcheck ./...
      - revive ./...
