version: '3'

tasks:
  default:
    desc: default (print all ifs)
    cmds:
      - go run main.go
  openlive:
    desc: Run pcap.OpenLive() example
    dir: cmd/openlive
    cmds:
      - go build
      - sudo ./openlive
  openoffline:
    desc: Run pcap.OpenOffline() example
    dir: cmd/openoffline
    cmds:
      - go build
      - cmd: sudo timeout 3s tcpdump -i eth0 -w example.pcap 'tcp'
        ignore_error: true
      - sudo ./openoffline
  bpffilter:
    desc: Run pcap.OpenLive() with BPF Filter
    dir: cmd/bpffilter
    cmds:
      - go build
      - cmd: sudo timeout 3s tcpdump -i lo -w example.pcap &
        ignore_error: true
      - cmd: timeout 3s ping localhost
        ignore_error: true
      - sudo ./bpffilter
  fmtvet:
    desc: go fmt and go vet
    cmds:
      - go fmt ./...
      - go vet ./...
      - staticcheck ./...
      - revive ./...
